# Generated by Django 5.2.8 on 2025-11-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=100)),
                ('serial_Number', models.IntegerField()),
                ('manufacture_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('product_quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('delivery_date', models.DateField()),
            ],
        ),
    ]
